version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eligcred-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./storage/app/models:/var/www/storage/app/models
    networks:
      - eligcred-network

  nginx:
    image: nginx:alpine
    container_name: eligcred-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - eligcred-network

  db:
    image: mysql:8.0
    container_name: eligcred-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - eligcred-network

networks:
  eligcred-network:
    driver: bridge 