[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "apache2-foreground"
healthcheckPath = "/index.html"
healthcheckTimeout = 900
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.healthcheck]
interval = "120s"
timeout = "60s"
retries = 3
startPeriod = "180s" 